# Generated by Django 4.0.2 on 2022-04-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50, verbose_name='Name')),
                ('comment', models.TextField(verbose_name='Comment')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='Question: ', max_length=100, verbose_name='Question')),
                ('answer', models.TextField(default='Manager will give the answer...', verbose_name='Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50, verbose_name='Service name')),
                ('service_cost', models.CharField(max_length=20, verbose_name='Service cost')),
                ('about', models.TextField(verbose_name='About service')),
                ('service_icon', models.ImageField(upload_to='')),
            ],
        ),
    ]
