# Generated by Django 4.0.2 on 2022-04-04 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='service_icon',
        ),
    ]
